# Site settings
title: Technical Services Department
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Princeton University Library's Technical Services Department
baseurl: "/tsd/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed